### ISSUE TITLE
LOH flags about battenberg file

### ISSUE THREAD

**Issue by MiaoGaoUK** [LCR-BCCRC/lcr-scripts#36]
Hi 

I want to ask about the get_loh_flag function of BattenbergParser in cnv2igv.py file(1.4 version). I am quiet confused about the loh type "neutral" and it's function (if int(nMaj1_A) == 2 and int(nMin1_A) == 1:  loh_flag = '1' ). I thought in the neutral situation, the nMin1_A should be 0. Could you please tell me how to define this flag here?

**Comment by Kdreval** [comment]
Hi @MiaoGaoUK 
I think you are right, and therefore the condition `int(nMin1_A) == 1` will not be satisfied in the `neutral` mode, and the resulting LOH flag will be returned as 0 following the execution of [this](https://github.com/LCR-BCCRC/lcr-scripts/blob/a45748a8d77ef1b4e03fa06f5d2f4bd92fc6066d/cnv2igv/1.4/cnv2igv.py#L161) line.
Of note, we usually run the cnv2igv in the `all` mode (which is set by default).

**Comment by davidwedge** [comment]
Hi @Kdreval ,
I think the LOH flag should be set to true, i.e. 1, if nMin1_A ==0 at line 163, rather than if nMin1_A==1

**Comment by rdmorin** [comment]
Thanks for catching this @davidwedge and @MiaoGaoUK !

**Comment by Kdreval** [comment]
This issue was resolved in the commit #38
