### ISSUE TITLE
fishHook smg input only made for GRCh37

### ISSUE THREAD

**Issue by gillissierra** [LCR-BCCRC/lcr-scripts#60]
Similar to other tools, a section will be added to ensure fishHook is only run on GRCh37 (hg19) genome build.
```
cat("Requested mode is HotMAPS, but the supplied file is in the hg38-based coordinates.\n")
    cat("Unfortunately, HotMAPS is configured to only work for grch37-based maf files.\n")
    stop("Please supply the mutation data in grch37-based version.")
```

**Comment by Kdreval** [comment]
This can be closed now?

**Comment by gillissierra** [comment]
No quite yet, I haven't made the change or tested it yet

**Comment by gillissierra** [comment]
Since the module is set up optionally use a gene list, I don't think this should be incorporated. The default is to use tiles which can be done for either genome build. Users can ensure themselves that their provided gene list corresponds to the correct genome build.
